export const NOTE_TYPES = {
  CREATE_NOTE: "CREATE_NOTE",
  GET_ALL_NOTE: "GET_ALL_NOTE",
  GET_ONE_NOTE: "GET_ONE_NOTE",
  GET_MY_NOTE: "GET_MY_NOTE",
  DELETE_NOTE: "DELETE_NOTE",
  EDIT_NOTE: "EDIT_NOTE",
};